# Change these first
owner: pastis-hosting # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: argocd
    url: https://argocd.pastis-hosting.net
  - name: keycloak
    url: https://keycloak.pastis-hosting.net
  - name: status
    url: https://status.pastis-hosting.net
  - name: www
    url: https://www.pastis-hosting.net

assignees:
  - trivoallan

status-website:
  cname: status.pastis-hosting.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: État des services
