owner: pastis-hosting
repo: status

sites:
  - name: argocd
    url: https://argocd.pastis-hosting.net
  - name: keycloak
    url: https://keycloak.pastis-hosting.net
  - name: status
    url: https://status.pastis-hosting.net
  - name: www
    url: https://www.pastis-hosting.net

assignees:
  - trivoallan

status-website:
  cname: status.pastis-hosting.net
  name: Pastis Hosting
